image: node:10

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-2
  BUCKET_NAME: tsac18-stevanon-web-stage
  AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

build:
  stage: build
  script:
    - npm install --quiet
    - npm run build-prod
  artifacts:
    paths:
      - dist/photocontest
  cache:
    # paths:
    #   - node_modules/
    #   - semantic/

deployS3:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - build      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com  # This is the url of the bucket we saved before
    on_stop: clean_S3 # When the branch is merged, we clean up after ourself

clean_S3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME} --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual