image: node:10-alpine

stages:
  - build
  - deploy

variables:
  AWS_REGION: eu-west-1
  BUCKET_NAME_AWS: tsac18-stevanon-web
  BUCKET_NAME_VULTR: tsac18-stevanon-web-stage

# PROD
build-prod:
  stage: build
  script:
    - npm install --quiet
    - npm run build-prod
  artifacts:
    paths:
      - dist/photocontest
  only:
    - tags
  except:
    - branches

deploy-prod-S3:
  image: python:latest
  stage: deploy
  dependencies:
    - build-prod
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_AWS} --recursive
  environment:
    name: production
    url: http://${BUCKET_NAME_AWS}.s3-website-${AWS_REGION}.amazonaws.com
  only:
    - tags
  except:
    - branches

# DEV
build-dev:
  stage: build
  script:
    - npm install --quiet
    - npm run build-stage
  artifacts:
    paths:
      - dist/photocontest
  only:
    - dev

deploy-dev-S3:
  image: python:latest
  stage: deploy
  dependencies:
    - build-dev
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_VULTR} --recursive
  environment:
    name: development
    url: http://${BUCKET_NAME_VULTR}.s3-website-${AWS_REGION}.amazonaws.com
    on_stop: clean_dev_deploy_S3
  only:
    - dev

# MANUAL JOBS
clean_dev_deploy_S3:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME_VULTR} --recursive
  environment:
    name: development
    action: stop
  only:
    - dev
  when: manual