image: node:10-alpine

stages:
  - build
  - deploy

variables:
  AWS_REGION: eu-west-1
  BUCKET_NAME_PROD: tsac18-stevanon-web
  BUCKET_NAME_STAGE: tsac18-stevanon-web-stage



#################### PRODUCTION ####################

# PRODUCTION BUILD
build-prod:
  stage: build
  script:
    - npm install --quiet
    - npm run build-prod
  artifacts:
    paths:
      - dist/photocontest
  only:
    - master
    - tags

# PRODUCTION DEPLOY
deployS3-prod:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build-prod
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_PROD} --recursive
  environment:
    name: production
    url: http://${BUCKET_NAME_PROD}.s3-website-${AWS_REGION}.amazonaws.com
  only:
    - master
    - tags


#################### STAGING ####################

# STAGIN BUILD
build-stage:
  stage: build
  script:
    - npm install --quiet
    - npm run build-stage
  artifacts:
    paths:
      - dist/photocontest
  only:
    - dev

# STAGIN DEPLOY
deployS3-stage:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build-stage
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_STAGE} --recursive
  environment:
    name: staging
    url: http://${BUCKET_NAME_STAGE}.s3-website-${AWS_REGION}.amazonaws.com
    #on_stop: clean_S3_stage
  only:
    - dev


#################### JOBS ####################

# clean_S3_stage:
#   image: "python:latest"
#   stage: deploy
#   before_script:
#     - pip install awscli
#   script:
#     - aws s3 rm s3://${BUCKET_NAME_STAGE} --recursive
#   environment:
#     name: staging
#     action: stop
#   only:
#     - dev
#   when: manual