image: node:10

stages:
  - build
  - deploy

variables:
  AWS_REGION: eu-west-1
  BUCKET_NAME_PROD: tsac18-stevanon-web
  BUCKET_NAME_STAGE: tsac18-stevanon-web-stage

build:
  stage: build
  script:
    - npm install --quiet
    - npm run build-prod
  artifacts:
    paths:
      - dist/photocontest

deployS3-prod:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_PROD} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME_PROD}.s3-website-${AWS_REGION}.amazonaws.com
  only:
  - master

deployS3-stage:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_STAGE} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME_STAGE}.s3-website-${AWS_REGION}.amazonaws.com
    on_stop: clean_S3_stage
  only:
  - dev


# Manual Jobs
clean_S3_stage:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME_STAGE} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual