image: node:10-alpine

stages:
  - build
  - deploy

# PROD
build-prod:
  stage: build
  script:
    - npm install --quiet
    - npm run build-prod
  artifacts:
    paths:
      - dist/photocontest
  only:
    - tags

deploy-prod-S3:
  image: python:latest
  stage: deploy
  dependencies:
    - build-prod
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_PROD} --recursive
  environment:
    name: production
    url: http://${BUCKET_NAME_PROD}.s3-website-${AWS_REGION}.amazonaws.com
  only:
    - tags

# DEV
build-dev:
  stage: build
  script:
    - npm install --quiet
    - npm run build-stage
  artifacts:
    paths:
      - dist/photocontest
  only:
    - dev

deploy-dev-S3:
  image: python:latest
  stage: deploy
  dependencies:
    - build-dev
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist/photocontest s3://${BUCKET_NAME_DEV} --recursive
  environment:
    name: dev
    url: http://${BUCKET_NAME_DEV}.s3-website-${AWS_REGION}.amazonaws.com
    on_stop: clean_dev_S3
  only:
    - dev

# MANUAL JOBS
clean_dev_S3:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME_DEV} --recursive
  environment:
    name: dev
    action: stop
  only:
    - dev
  when: manual