version: "3"

services:
  photocontest.marcostevanon.ovh:
    container_name: photocontest.marcostevanon.ovh
    image: registry.gitlab.com/its-photocontest/web-client:dev
    restart: always
    labels:
      - "traefik.frontend.rule=Host:photocontest.marcostevanon.ovh"
      - "traefik.port=80"
      - "traefik.enable=true"
    networks:
      - traefik

networks:
  traefik:
    external: true